services:
    - type: web
      name: gut-feel
      env: python
      buildCommand: pip install -r requirements.txt
      startCommand: uvicorn telegram_bot:app --host 0.0.0.0 --port $PORT
      envVars:
          - key: TELEGRAM_BOT_TOKEN
            sync: false
          - key: GOOGLE_STUDIO_API_KEY
            sync: false
          - key: FFH_EMAIL
            sync: false
          - key: FFH_PASSWORD
            sync: false
